In [6]:
from imutils import contours
import imutils
import cv2
import numpy as np
 

image = cv2.imread("sample.png")
 
image = imutils.resize(image, height=500)
cv2.imshow('Image', image)
cv2.waitKey(10000)  
cv2.destroyAllWindows()

contrast = cv2.convertScaleAbs(image, alpha=5, beta=90)
cv2.imshow('Contrast', contrast)
cv2.waitKey(10000)  
cv2.destroyAllWindows()

gray = cv2.cvtColor(contrast, cv2.COLOR_BGR2GRAY)
cv2.imshow('Gray', gray)
cv2.waitKey(10000)  
cv2.destroyAllWindows()

threshold = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)[1]
cv2.imshow('Threshold', threshold)
cv2.waitKey(10000)  
cv2.destroyAllWindows()

kernel = cv2.getStructuringElement(cv2.MORPH_CROSS, (15, 15))
cv2.imshow('Kernel', kernel)
cv2.waitKey(10000)  
cv2.destroyAllWindows()

img = cv2.morphologyEx(threshold, cv2.MORPH_OPEN, kernel)
cv2.imshow('Img', img)
cv2.waitKey(10000)  
cv2.destroyAllWindows()

cnts = cv2.findContours(img.copy(), cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
cnts = imutils.grab_contours(cnts)
#cv2.drawContours(image,cnts,-1,(0, 255, 0), 2)
boundingRect = []
for c in cnts:
    (x, y, w, h) = cv2.boundingRect(c)
    if (h > image.shape[0]*0.3 and h <image.shape[0]*0.9):    
        cv2.rectangle(image,(x,y),(x+w,y+h),(0, 0, 255), 2)
        boundingRect.append([x,y,w,h])

#cv2.drawContours(image,cnts,-1,(0, 255, 0), 2)
boundingRect = sorted(boundingRect, key=lambda boundingRect: boundingRect[0])

standard = 50
test_data = []
for r in boundingRect:
    (x, y, w, h) = r
    d = imutils.resize(threshold[y:y + h, x:x + w], height=standard,width=standard) 
    print(d.shape)
    tmp_h, tmp_w = d.shape
    #padding white pixel to make the digit in square scale
    ptop = int((standard * 2 - tmp_h) / 2)
    pbuttom = standard * 2  - ptop - tmp_h
    pleft = int((standard * 2  - tmp_w) / 2)
    pright = standard * 2 - pleft - tmp_w
    print(str(ptop) + '-' + str(pbuttom) + '-' + str(pleft) + '-' + str(pright))    
    if (ptop > 0 and pbuttom > 0 and pleft > 0 and pright > 0):
        constant = cv2.copyMakeBorder(d,ptop,pbuttom,pleft,pright,cv2.BORDER_CONSTANT,value=[255,255,255])
        print(constant.shape)    
        reshape = imutils.resize(constant, height=standard,width=standard)     
        cv2.imshow("Image", reshape)   
        cv2.waitKey(10000)
        cv2.destroyAllWindows()
        test_data.append(reshape)    
    

test_data = np.asarray(test_data, dtype=np.float32)
print(f"test_data : {test_data.shape}")
test_data = np.reshape(test_data,(test_data.shape[0],standard*standard))
print(f"test_data : {test_data.shape}")

#load model
model2 = cv2.ml.SVM_load("model.xml")
_, y_val = model2.predict(test_data)
print("prediction result")
print(f"np.int_(y_val) : {np.int_(y_val)}")


cv2.imshow("Image", image)   
cv2.waitKey(10000)  
cv2.destroyAllWindows()

(70, 50)
15-15-25-25
(100, 100)
(77, 50)
11-12-25-25
(100, 100)
(68, 50)
16-16-25-25
(100, 100)
(78, 50)
11-11-25-25
(100, 100)
test_data : (4, 50, 50)
test_data : (4, 2500)
prediction result
np.int_(y_val) : [[2]
 [3]
 [4]
 [5]]


In [1]:
from imutils import contours
import imutils
import cv2
import numpy as np
 

image = cv2.imread("cropped.jpeg")
#image = cv2.imread("a.jpeg") 
#image = cv2.imread("w.jpeg")
#image = cv2.imread("weight_machine1.jpeg")

image = imutils.resize(image, height=500)
cv2.imshow('Image', image)
cv2.waitKey(10000)  
cv2.destroyAllWindows()

#contrast = cv2.convertScaleAbs(image, alpha=5, beta=90)
#cv2.imshow('Contrast', contrast)
#cv2.waitKey(10000)  
#cv2.destroyAllWindows()

#gray = cv2.cvtColor(contrast, cv2.COLOR_BGR2GRAY)
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.imshow('Gray', gray)
cv2.waitKey(10000)  
cv2.destroyAllWindows()

threshold = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)[1]
cv2.imshow('Threshold', threshold)
cv2.waitKey(10000)  
cv2.destroyAllWindows()

kernel = cv2.getStructuringElement(cv2.MORPH_CROSS, (15, 15))
cv2.imshow('Kernel', kernel)
cv2.waitKey(10000)  
cv2.destroyAllWindows()


#img = cv2.morphologyEx(threshold_dilated, cv2.MORPH_OPEN, kernel)
img = cv2.morphologyEx(threshold, cv2.MORPH_OPEN, kernel)

cv2.imshow('Img', img)
cv2.waitKey(10000)  
cv2.destroyAllWindows()

#dilation = cv2.dilate(img,kernel,iterations = 1)
erosion = cv2.erode(img,kernel,iterations = 1)
cv2.imshow('Erosion', erosion)
#cv2.imwrite("erosion1.jpeg", erosion)
cv2.waitKey(10000)
cv2.destroyAllWindows()


cnts = cv2.findContours(erosion.copy(), cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
cnts = imutils.grab_contours(cnts)
#cntss = cv2.drawContours(image,cnts,-1,(0, 255, 0), 2)
#cv2.imshow('Cntssss', cntss)
#cv2.imwrite("Cnts_dilated1.jpeg", cntss)
#cv2.waitKey(10000)  
#cv2.destroyAllWindows()




#cv2.drawContours(image,cnts,-1,(0, 255, 0), 2)
boundingRect = []
for c in cnts:
    (x, y, w, h) = cv2.boundingRect(c)
    if (h > image.shape[0]*0.3 and h <image.shape[0]*0.9):    
        cv2.rectangle(image,(x,y),(x+w,y+h),(0, 0, 255), 2)
        boundingRect.append([x,y,w,h])

#cv2.drawContours(image,cnts,-1,(0, 255, 0), 2)
boundingRect = sorted(boundingRect, key=lambda boundingRect: boundingRect[0])
print(f'Bounding Rect: {boundingRect}')

standard = 50
test_data = []
for r in boundingRect:
    (x, y, w, h) = r
    d = imutils.resize(threshold[y:y + h, x:x + w], height=standard,width=standard) 
    print(d.shape)
    tmp_h, tmp_w = d.shape
    #padding white pixel to make the digit in square scale
    ptop = int((standard * 2 - tmp_h) / 2)
    pbuttom = standard * 2  - ptop - tmp_h
    pleft = int((standard * 2  - tmp_w) / 2)
    pright = standard * 2 - pleft - tmp_w
    print(str(ptop) + '-' + str(pbuttom) + '-' + str(pleft) + '-' + str(pright))    
    if (ptop > 0 and pbuttom > 0 and pleft > 0 and pright > 0):
        constant = cv2.copyMakeBorder(d,ptop,pbuttom,pleft,pright,cv2.BORDER_CONSTANT,value=[255,255,255])
        print(constant.shape)    
        reshape = imutils.resize(constant, height=standard,width=standard)     
        cv2.imshow("Reshape_test", reshape)   
        cv2.waitKey(10000)
        cv2.destroyAllWindows()
        test_data.append(reshape)    
    

test_data = np.asarray(test_data, dtype=np.float32)
print(f"test_data : {test_data.shape}")
test_data = np.reshape(test_data,(test_data.shape[0],standard*standard))
print(f"test_data : {test_data.shape}")

#load model
model2 = cv2.ml.SVM_load("ocr_model.pkl")
# Check if the model is loaded properly
#if model2.empty():
#    print("Error loading the model.")
#else:
#    # Ensure the test data is in the correct shape for prediction
#    if test_data.shape[0] > 0:
#        # Predict using the loaded SVM model
#        _, y_val = model2.predict(test_data)
#        
#        # Check if prediction is successful
#        if y_val is not None:
#            # Convert y_val to integers
#            y_val = y_val.astype(int)
#            print("Prediction result:")
#            print(y_val)
#        else:
#            print("Prediction failed.")
#    else:
#        print("No test data available.")
#load model
_, y_val = model2.predict(test_data)
print("prediction result")
print(f"np.int_(y_val) : {np.int_(y_val)}")


cv2.imshow("Image", image)   
cv2.waitKey(10000)  
cv2.destroyAllWindows()

Bounding Rect: [[1151, 249, 183, 199], [1159, 52, 182, 198], [1401, 45, 160, 198], [1484, 242, 62, 182]]
(54, 50)
23-23-25-25
(100, 100)
(54, 50)
23-23-25-25
(100, 100)
(61, 50)
19-20-25-25
(100, 100)
(146, 50)
-23--23-25-25
test_data : (3, 50, 50)
test_data : (3, 2500)
prediction result
np.int_(y_val) : [[3]
 [5]
 [0]]


In [13]:
from imutils import contours
import imutils
import cv2
import numpy as np
 

image = cv2.imread("cropped.jpeg")
#image = cv2.imread("a.jpeg") 
#image = cv2.imread("w.jpeg")
#image = cv2.imread("weight_machine1.jpeg")

image = imutils.resize(image, height=500)
cv2.imshow('Image', image)
cv2.waitKey(10000)  
cv2.destroyAllWindows()

#contrast = cv2.convertScaleAbs(image, alpha=5, beta=90)
#cv2.imshow('Contrast', contrast)
#cv2.waitKey(10000)  
#cv2.destroyAllWindows()

#gray = cv2.cvtColor(contrast, cv2.COLOR_BGR2GRAY)
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.imshow('Gray', gray)
cv2.waitKey(10000)  
cv2.destroyAllWindows()

threshold = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)[1]
cv2.imshow('Threshold', threshold)
cv2.waitKey(10000)  
cv2.destroyAllWindows()

kernel = cv2.getStructuringElement(cv2.MORPH_CROSS, (15, 15))
cv2.imshow('Kernel', kernel)
cv2.waitKey(10000)  
cv2.destroyAllWindows()


#img = cv2.morphologyEx(threshold_dilated, cv2.MORPH_OPEN, kernel)
img = cv2.morphologyEx(threshold, cv2.MORPH_OPEN, kernel)

cv2.imshow('Img', img)
cv2.waitKey(10000)  
cv2.destroyAllWindows()

cnts = cv2.findContours(img.copy(), cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
cnts = imutils.grab_contours(cnts)
cv2.drawContours(image,cnts,-1,(0, 255, 0), 2)
boundingRect = []
for c in cnts:
    (x, y, w, h) = cv2.boundingRect(c)
    if (h > image.shape[0]*0.3 and h <image.shape[0]*0.9):    
        cv2.rectangle(image,(x,y),(x+w,y+h),(0, 0, 255), 2)
        boundingRect.append([x,y,w,h])

#cv2.drawContours(image,cnts,-1,(0, 255, 0), 2)
boundingRect = sorted(boundingRect, key=lambda boundingRect: boundingRect[0])

standard = 50
test_data = []
for r in boundingRect:
    (x, y, w, h) = r
    d = imutils.resize(threshold[y:y + h, x:x + w], height=standard,width=standard) 
    print(d.shape)
    tmp_h, tmp_w = d.shape
    constant = cv2.copyMakeBorder(d,5,5,5,5, cv2.BORDER_CONSTANT,value=[255,255,255])
    print(constant.shape)    
    reshape = imutils.resize(constant, height=standard,width=standard)     
    cv2.imshow("Imagvfdge", reshape)   
    cv2.waitKey(10000)
    cv2.destroyAllWindows()
    test_data.append(reshape)    
    for item in test_data:
        print(f"item : {item}")

test_data = np.asarray(test_data, dtype=np.float32)
print(f"test_data : {test_data.shape}")

test_data = np.reshape(test_data,(test_data.shape[0],standard*standard))
print(f"test_data : {test_data.shape}")

#load model
model2 = cv2.ml.SVM_load("ocr_model.pkl")
# Check if the model is loaded properly
if model2.empty():
    print("Error loading the model.")
else:
    # Ensure the test data is in the correct shape for prediction
    if test_data.shape[0] > 0:
        # Predict using the loaded SVM model
        _, y_val = model2.predict(test_data)
        
        # Check if prediction is successful
        if y_val is not None:
            # Convert y_val to integers
            y_val = y_val.astype(int)
            print("Prediction result:")
            print(y_val)
        else:
            print("Prediction failed.")
    else:
        print("No test data available.")



cv2.imshow("Image", image)   
cv2.waitKey(10000)  
cv2.destroyAllWindows()

(54, 50)
(64, 60)
item : [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
(54, 50)
(64, 60)
item : [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
item : [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
(63, 50)
(73, 60)
item : [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
item : [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [9]:
from imutils import contours
import imutils
import cv2
import numpy as np
 

image = cv2.imread("cropped.jpeg")
 
image = imutils.resize(image, height=500)


contrast = cv2.convertScaleAbs(image, alpha=5, beta=90)

gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)


threshold = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)[1]


kernel = cv2.getStructuringElement(cv2.MORPH_CROSS, (15, 15))


img = cv2.morphologyEx(threshold, cv2.MORPH_OPEN, kernel)


#dilation = cv2.dilate(img,kernel,iterations = 1)
erosion = cv2.erode(img,kernel,iterations = 2)
cv2.imshow('Erosion', erosion)
cv2.imwrite("erosion_testing.jpeg", erosion)
cv2.waitKey(10000)
cv2.destroyAllWindows()


cnts = cv2.findContours(erosion.copy(), cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
cnts = imutils.grab_contours(cnts)
cntss = cv2.drawContours(image,cnts,-1,(0, 255, 0), 2)
cv2.imshow('Cntssss', cntss)
cv2.imwrite("cnts_erosion_testing.jpeg", cntss)
cv2.waitKey(10000)  
cv2.destroyAllWindows()


In [11]:
import cv2
import numpy as np

# Load model
test_data = []
pic = cv2.imread("Cnts_dilated.jpeg")
test_data.append(pic)

model2 = cv2.ml.SVM_load("ocr_model.pkl")

# Check if the model is loaded properly
if model2.empty():
    print("Error loading the model.")
else:
    # Ensure the test data is in the correct shape for prediction
    if len(test_data) > 0:
        # Resize and flatten each image in the test data
        resized_data = [cv2.resize(img, (50, 50)) for img in test_data]  # Resize images to match model's expected input size
        flattened_data = [img.flatten() for img in resized_data]  # Flatten each resized image
        
        # Convert test_data to a NumPy array
        test_data = np.array(flattened_data)
        
        # Convert test_data to the correct data type
        test_data = test_data.astype(np.float32)
        
        # Predict using the loaded SVM model
        _, y_val = model2.predict(test_data)
        
        # Check if prediction is successful
        if y_val is not None:
            # Convert y_val to integers
            y_val = y_val.astype(int)
            print("Prediction result:")
            print(y_val)
        else:
            print("Prediction failed.")
    else:
        print("No test data available.")

# Display the image
cv2.imshow("Image", pic)
cv2.waitKey(10000)
cv2.destroyAllWindows()


error: OpenCV(4.9.0) /io/opencv/modules/ml/src/svm.cpp:2007: error: (-215:Assertion failed) samples.cols == var_count && samples.type() == CV_32F in function 'predict'


In [3]:
import cv2
import imutils
#predict image
test_data = []
filename = 'erosion.jpeg'
img = cv2.imread(filename)
img = imutils.resize(img, height=50,width=50)
#img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imshow("Image",img)
cv2.waitKey(10000)  
cv2.destroyAllWindows()

